### ISSUE TITLE
clarify how to contribute / collaborate

### ISSUE THREAD

**Issue by aspiers** [OpenStack-mobile/summit-app-android#10]
Hi there,

Really awesome that this is on github!  Please can you update the README (or create a `CONTRIBUTING.md`) in order to clarify where bugs / feature requests etc. should be submitted, and whether pull requests are welcome here or should gerrit be used instead.

Thanks!

**Comment by jimmytipit** [comment]
Thanks for filing the issue and again, apologies for the long time for the response. For now, all bugs should be submitted to summitapps@openstack.org. We'll update the documentation with this info after the current summit. 

The apps will be moving to Gerrit shortly after the Barcelona Summit, but in the meantime, pull requests can be made via github. I'll also clarify this in the documentation.

**Comment by aspiers** [comment]
Thanks a lot for the response, but I beg you to reconsider and standardize an **open** issue tracker for this.  This Zendesk support system is a black box which goes directly against the ethos of [OpenStack's four Opens](https://wiki.openstack.org/wiki/Open).  It is also an extremely inefficient way of developing software, for reasons which I would hope are obvious enough to anyone who works within OpenStack and understands the benefit of its openness that I wouldn't need to enumerate them.  For example, the ability to search, browse, and contribute to all existing issues previously submitted is absolutely paramount.

What I am asking for could be implemented literally within a matter of minutes.  For example, you could declare this GitHub issue tracker as the official place to track issues.  Or you could set up a launchpad project and use that bug tracker.  Either would be perfectly adequate and far better than a system where 100 people could be reporting the same bug as each other all at the same time, without any having knowledge of the reports of the others.

**Comment by smarcet** [comment]
Hello Adam, apologies for the long time for the response. As you suggested we will be start using this 
https://github.com/OpenStack-mobile/summit-app-android/issues as official issue tracker to collect all bugs and feedback, thank you for your patience 

Regards

**Comment by aspiers** [comment]
[**@smarcet**](https://github.com/smarcet) commented on [12 Nov 2018, 12:22 GMT](https://github.com/OpenStack-mobile/summit-app-android/issues/10#issuecomment-437859715 "2018-11-12T12:22:52Z - Replied by Github Reply Comments"):
> sure good point will do  
> 
> regards

Thanks!  BTW has this plan been abandoned or just postponed?

[**@jimmytipit**](https://github.com/jimmytipit) commented on [25 Oct 2016, 10:43 BST](https://github.com/OpenStack-mobile/summit-app-android/issues/10#issuecomment-255987936 "2016-10-25T09:43:23Z - Replied by Github Reply Comments"):
> The apps will be moving to Gerrit shortly after the Barcelona Summit, but in the meantime, pull requests can be made via github. I'll also clarify this in the documentation.

**Comment by jimmytipit** [comment]
@aspiers The move to gerrit has just been postponed. We've been working on moving our sites to a new data center, which has required a whole bunch of unanticipated additional work.  At some point... we will move to Gerrit ;)

**Comment by aspiers** [comment]
Got it, thanks for the info!

**Comment by aspiers** [comment]
I'll submit a new issue for clarity.  The general question here has been answered.
